module.exports = TextDescription =
  headtitle : '标题'
  cancel : '取消'
  next : '下一步'
  prev : '上一步'
  upload : '上传'
  back : '返回'
  finish : '完成'
  login : '登录'
  logout : '退出登录'
  email : '邮箱'
  pwd : '密码'
  save : '保存'
  createProject : '创建项目'
  createModule : '创建模块'
  newProject: '新建项目'
  syncProject: '同步账号中的项目'
  registerUrl : ''
  newProjectDefaultPath: atom.config.get('core').projectHome
  appConfigPath: atom.project.getPaths()[0]+'\\config\\appconf.txt'
  moduleConfigPath: atom.project.getPaths()[0]+'\\config\\moduleconf.txt'
  configPath: atom.project.getPaths()[0]+'\\config'
  iconPath:'atom://chameleon-qdt-atom/images/icon.png'
  mainEntry: 'index.html'
