module.exports = TextDescription =
  headtitle : '标题'
  cancel : '取消'
  next : '下一步'
  prev : '上一步'
  upload : '上传'
  finish : '完成'
  login : '登录'
  logout : '退出登录'
  email : '邮箱'
  pwd : '密码'
  save : '保存'
  createProject : '创建项目'
